### ISSUE TITLE
Performance improvements for next release

### ISSUE THREAD

**Issue by goferHiro** [bxcodec/dbresolver#20]
![image](https://user-images.githubusercontent.com/103487904/206908163-398185d9-29bb-4730-b200-4e78d66beb8a.png)

1. Use pass by pointer instead of value
2. Replace context.Background with a global value

**Comment by bxcodec** [comment]
> Replace context.Background with a global value
I don't think this is a wise solution 🤔

**Comment by goferHiro** [comment]
Pointers - same memory space. One less asm instruction - "MOV"

**Comment by goferHiro** [comment]
databases are going to constant through out the lifecycle of the application

**Comment by goferHiro** [comment]
Closing this issue

<Summary>

- Use pass by pointer instead of value- memory leaks/readability outweighs performance greatly
- Replace context.Background with a global value - will cause issues when one query fails could cause cascading failing in other queries running concurrently and all other queries that run in futures
