### ISSUE TITLE
User improvements for next release

### ISSUE THREAD

**Issue by goferHiro** [bxcodec/dbresolver#21]
1. Update doc

https://user-images.githubusercontent.com/11002383/180010864-c9e2a0b6-520d-48d6-bf0d-490eb070e75d.png

2. Create doc.go

**Comment by goferHiro** [comment]
@bxcodec  wondering which S/W generated these images

**Comment by bxcodec** [comment]
It's draw.io
With sketched style

**Comment by goferHiro** [comment]
cool
