### ISSUE TITLE
Request: Contributor Access

### ISSUE THREAD

**Issue by Nasfame** [bxcodec/dbresolver#35]
Dear @bxcodec,

I hope this email finds you well. I am writing to express my interest in maintaining [dbresolver](https://github.com/bxcodec). After closely following the project and using it in my own work, I believe I can make valuable contributions to its development.

Thank you for considering my request. I look forward to the opportunity and collaborate with you.

Best regards,
Hiro

**Comment by bxcodec** [comment]
Hi @Nasfame , 

I've added you, can you check again?

**Comment by Nasfame** [comment]
Thanks @Nasfame
