### ISSUE TITLE
Unexpected concurrent behaviour

### ISSUE THREAD

**Issue by newtonis** [bxcodec/dbresolver#44]
![image](https://github.com/bxcodec/dbresolver/assets/6299385/9497313c-863e-4ab0-ad15-201c4eb6f0fb)

Hi, this lines with channels generate unexpeted concurrency behaviour when running multiple threads i.e some of the threads ends on timeout because are not unlocked. We had a long time debugging this behaviour in our project and finding that the problem was here.

**Comment by Nasfame** [comment]
@newtonis We are sorry for the inconvenience.

**Comment by Nasfame** [comment]
@newtonis Cheers!!! Just patched the logic. You shouldn't face deadlocks with the patch

**Comment by newtonis** [comment]
Hi, we will use patched logic then. We will report if we find any failure.

Thank you !!

**Comment by Nasfame** [comment]
@newtonis u can do `go get github.com/bxcodec/dbresolver@v2.1.1-beta` .

**Comment by newtonis** [comment]
Hi, I just run the command, I get the following error
go get github.com/bxcodec/dbresolver@v2.1.2-beta
go: github.com/bxcodec/dbresolver@v2.1.2-beta: invalid version: go.mod has post-v2 module path "github.com/bxcodec/dbresolver/v2" at revision v2.1.2-beta

**Comment by Nasfame** [comment]
@newtonis fixed the command

**Comment by newtonis** [comment]
Hi. 
I can confirm I did 'go get github.com/bxcodec/dbresolver/v2@v2.1.2-beta' and issue was solved under my tests.

**Comment by Nasfame** [comment]
@newtonis Awesome, @bxcodec #45 is ready.

**Comment by Nasfame** [comment]
@newtonis Can u share the test here? or update at 

https://github.com/bxcodec/dbresolver/blob/main/db_test.go

https://github.com/bxcodec/dbresolver/blob/main/loadbalancer_test.go

I couldn't replicate ur scenario unfortunately. if u can share the configuration of DBResolver .. u used, it would be of help too

**Comment by Nasfame** [comment]
Thanks that helps...

**Comment by Nasfame** [comment]
@newtonis can u share the resolver configuration as well. No of Replica DBs, and primary DBs?

**Comment by newtonis** [comment]
My test is configured with 1 database (rw) and no replica, I believe you
should be able to reproduce the same under that conditions and just the
query method. Let me now if you can't

Thank you!!
